services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.frontend

    ports:
      - "80:80"

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile.backend

    volumes:
      - data:/app

    ports:
      - "5000:5000"

volumes:
  data:
  
  
