services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.frontend

    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend

    ports:
      - "5000:5000"

    volumes:
      - ./backend:/app
    
    environment:
      - FLASK_APP=application.py
      - FLASK_ENV=development
    command: flask --app application.py run --host=0.0.0.0

