FROM python:3.13-slim

WORKDIR /app

COPY . .

# Install pip and dependencies directly
RUN apt-get update && apt-get install -y gcc libpq-dev
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

CMD ["flask", "--app", "application.py", "run", "--host=0.0.0.0"]
